### ISSUE TITLE
[T0] Duda con "máximo 8 horas después"

### ISSUE THREAD

**Issue by JoMarchant** [IIC2283/DAA-2022-2#3]
Hola,

Mi duda es si se incluye el minuto en que se cumplen 8 horas, siendo el intervalo de minutos válidos para escoger $[0, 480]$ incluyendo extremos. O solo se considera hasta el minuto 479?

Muchas gracias

**Comment by N9199** [comment]
Si, en efecto el intervalo de minutos válidos es inclusivo-inclusivo.

**Comment by CrisBerriosL** [comment]
Otra duda similar, pero para las actividades. Si hay una actividad por ejemplo con S = 30 y con D = 30, entonces el intervalo de minutos de la actividad sería [30, 59] o [30, 60]?

**Comment by N9199** [comment]
El intervalo incluye S+D
