### ISSUE TITLE
[I2] Duda temario I2

### ISSUE THREAD

**Issue by javiinostroza** [IIC2283/DAA-2022-2#30]
Hola, para la I2 entra el Pequeño teorema de Fermat? Me queda la duda dado que lo vimos en ayudantía, sin embargo en las clases fue visto después de Introducción a algoritmos en Teoría de Números. 

Gracias de antemano 😄

**Comment by nicovsj** [comment]
Hola @javiinostroza,

No entra ese teorema pues lo vimos en la clase 19, y anunciamos que la materia de la prueba es hasta la clase 18. 

Saludos!
